# Configure pre-commit hooks to check for Python code validity, formatting and
# style issues and prompt for these to be corrected before committing.

repos:

  # Use specific format-enforcing pre-commit hooks from the core library
  # with the default configuration (see pre-commit.com for documentation).
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
        types: [python]

  # Also validate against 'black' for unambiguous Python formatting
  # (see https://black.readthedocs.io/en/stable/ for documentation and see
  # the pyproject.toml file for our custom black configuration).
  - repo: https://github.com/ambv/black
    rev: 21.5b0
    hooks:
      - id: black
        language_version: python3

  # Additionally validate againt flake8 for other Python style enforcement
  # where we take flake8 with default configuration.
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
